-- auto Generated on 2019-04-01
-- DROP TABLE IF EXISTS PERSON_TEST;
CREATE TABLE PERSON_TEST(
	id VARCHAR (50) NOT NULL AUTO_INCREMENT COMMENT 'id',
	name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	age INT (11) NOT NULL DEFAULT -1 COMMENT 'age',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'PERSON_TEST';
