spring:
  application:
    name: wdj
  datasource:
      name: wdj
      url: jdbc:oracle:thin:@10.128.134.134:1521:orcl
      username: wdj_test
      password: 123456
      driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  type-aliases-package:
  mapper-locations:
    - classpath:mybatis/*.xml
server:
  port: 8080